const express = require('express');
const cors = require('cors');
const { GoogleGenAI } = require('@google/genai');
const customers = require('./dataset.json');

// This explicitly initializes the system environment variables line lookup
require('dotenv').config();

const app = express();
app.use(express.json());
app.use(cors());

// Flawless Multi-environment configuration fallback hook
const apiKey = process.env.GEMINI_API_KEY || 'AQ.Ab8RN6Kwczsk8QhAvQuJp_GCH6ubJJwew8bd-woovxEfpG1eRQ';
const ai = new GoogleGenAI({ apiKey: apiKey });

let campaignStats = {
  totalSent: 0,
  delivered: 0,
  opened: 0,
  failed: 0
};

app.get('/api/customers', (req, res) => {
  res.json(customers);
});

app.get('/api/stats', (req, res) => {
  res.json(campaignStats);
});

// NEW AI-POWERED CAMPAIGN ROUTE
app.post('/api/campaigns/send', async (req, res) => {
  const { prompt, channel } = req.body; 
  // Example input: prompt = "Find inactive customers who haven't ordered in 90 days"

  if (!prompt || !channel) {
    return res.status(400).json({ error: "Prompt and channel are required." });
  }

  try {
    // 1. Ask Gemini to convert the plain English request into a clean JavaScript evaluation condition
    const aiResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `You are an API assistant for a CRM database. The database customer object has these numeric attributes: "totalOrders", "totalSpent", and "lastOrderDaysAgo".
      Convert this user request into a single JavaScript condition string: "${prompt}".
      Return ONLY the raw executable condition string. Do not include markdown block quotes, backticks, explanation, or 'javascript' text.
      Example user input: "customers who haven't ordered in 3 months"
      Example response: c.lastOrderDaysAgo > 90`
    });

    const filterConditionString = aiResponse.text.trim();
    console.log(`[AI LOG] Generated Filter Condition: ${filterConditionString}`);

    // 2. Safely apply the dynamic AI filter to our customer dataset
    const targetAudience = customers.filter(c => {
      try {
        // Evaluate the string condition generated by the AI safely
        return Function('c', `return ${filterConditionString}`)(c);
      } catch (err) {
        return false;
      }
    });

    if (targetAudience.length === 0) {
      return res.status(400).json({ message: "AI generated a filter, but zero customers matched the criteria." });
    }

    // 3. Increment stats and trigger the simulated asynchronous delivery loop
    campaignStats.totalSent += targetAudience.length;
    targetAudience.forEach(customer => {
      simulateChannelDelivery(customer, `Hi ${customer.name}! We miss you. Check out our latest collection!`, channel);
    });

    res.json({ 
      message: `AI generated segment condition: "${filterConditionString}". Campaign launched successfully to ${targetAudience.length} shoppers!`,
      audienceCount: targetAudience.length
    });

  } catch (error) {
    console.error("AI Generation Error:", error);
    res.status(500).json({ error: "Failed to process request with AI layer." });
  }
});

app.post('/api/crm/receipt', (req, res) => {
  const { status, customerId } = req.body;

  if (status === 'delivered') campaignStats.delivered++;
  if (status === 'opened') campaignStats.opened++;
  if (status === 'failed') campaignStats.failed++;

  console.log(`[CRM LOG] Updated status for ${customerId}: ${status}`);
  res.sendStatus(200);
});

function simulateChannelDelivery(customer, message, channel) {
  const receiptUrl = 'http://localhost:5000/api/crm/receipt';

  setTimeout(async () => {
    const isFailed = Math.random() < 0.05; 
    const finalStatus = isFailed ? 'failed' : 'delivered';

    try {
      await fetch(receiptUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ customerId: customer.id, status: finalStatus })
      });

      if (!isFailed) {
        setTimeout(async () => {
          const isOpened = Math.random() < 0.60; 
          if (isOpened) {
            await fetch(receiptUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ customerId: customer.id, status: 'opened' })
            });
          }
        }, 3000);
      }
    } catch (err) {
      console.error("Error sending receipt callback:", err.message);
    }
  }, 2000);
}

const PORT = 5000;
app.listen(PORT, () => {
  console.log(`CRM backend server is live on http://localhost:${PORT}`);
});